### ISSUE TITLE
it does not work with seek thermal XR

### ISSUE THREAD

**Issue by meitiever** [ethz-asl/seekthermal_ros#2]
Dear ethz-asl
     I tired this ros node today, but it does not work. could you help me figure it out please. thanks

error message:
[ERROR] [1457785321.671355817]: Tried to advertise a service that is already advertised in this node [/seekthermal_ros_node/compressedDepth/set_parameters]
[ERROR] [1457785321.689655883]: Tried to advertise a service that is already advertised in this node [/seekthermal_ros_node/compressed/set_parameters]
[ERROR] [1457785321.703937043]: Tried to advertise a service that is already advertised in this node [/seekthermal_ros_node/theora/set_parameters]
[ERROR] [1457785321.720175031]: Tried to advertise on topic [/seekthermal_ros_node] with md5sum [9608fc0145356b4c079fd63bb3bd179c] and datatype [seekthermal_ros/ThermalImage], but the topic is already advertised as md5sum [060021388200f6f0f447d0fcd9c64743] and datatype [sensor_msgs/Image]
[ERROR] [1457785321.723696184]: No devices found and no device specified in config file
terminate called after throwing an instance of 'SeekThermal::PointerSeekThermal::Interface::NullError'
  what():  Null pointer access
Aborted (core dumped)

thanks

**Comment by samuelba** [comment]
The problem might be that you use the XR version. We never tested the driver libseekthermal with that model and libseekthermal was writtern for the normal Seek Thermal Compact.

Did you actually install [libseekthermal](https://github.com/ethz-asl/libseekthermal) from source or from our [PPA](https://launchpad.net/~ethz-asl/+archive/ubuntu/drivers)?

To see if libseekthermal is working do the following:

```
lsusb
```

you will get something like this:

```
Bus 003 Device 002: ID 8087:8001 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 2109:0812 VIA Labs, Inc. VL812 Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 007: ID 8087:0a2a Intel Corp. 
Bus 001 Device 006: ID 289d:0010  
Bus 001 Device 003: ID 2109:2812 VIA Labs, Inc. VL812 Hub
Bus 001 Device 002: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

in this example it's the device without a description (`Bus 001 Device 006: ID 289d:0010`)

run:

```
seekthermal-view 001:006
```

if you see a new window with black and white image stream, the driver is working with the Compact XR camera, otherwise not. If not, please open an issue at [libseekthermal](https://github.com/ethz-asl/libseekthermal).

**Comment by billrock** [comment]
I have had no problem with either the Seek Compact or Seek XR using the libseekthermal library and seekthermal_ros.  I'm using it with an XR right now.

**Comment by samuelba** [comment]
@billrock thanks, than @meitiever probably has not installed libseekthermal. @meitiever if you did install libseekthermal, what Ubuntu version are you using?

**Comment by samuelba** [comment]
I guess the question is resolved.

**Comment by meitiever** [comment]
oh. sorry for late response.
I am working on another project these months.
I will try my XR device tomorrow.
thanks.

**Comment by meitiever** [comment]
@samuelba, I think i have got the error.
Firstly, i can run "sudo add-apt-repository ppa:ethz-asl/drivers" this on my NUC(ubuntu 16.04 LTS).
but, the command:"sudo apt-get update" returns "E: Failed to fetch http://ppa.launchpad.net/ethz-asl/drivers/ubuntu/dists/xenial/main/binary-amd64/Packages" and i found that it is a invalid URL.
Could you help me out of this please. thanks

By the way, does these drivers and packages compatible with Raspberry Pi(ARM arch)?
Does this driver work with Ubuntu 16.04?

thank you very much.

**Comment by samuelba** [comment]
@meitiever there is no libseekthermal driver debian package for 16.04. You have to build it from source https://github.com/ethz-asl/libseekthermal
I didn't test the driver with 16.04, but it should work.

**Comment by meitiever** [comment]
you mean I have to build the driver from source?

**Comment by samuelba** [comment]
yes, first you build/install remake (https://github.com/kralf/remake#building-from-source) from source and then libseekthermal (https://github.com/ethz-asl/libseekthermal#building-from-source) it's not that difficult.

**Comment by meitiever** [comment]
I have build and install remake successfully. it is easy.
but for libseekthermal. libudev is missing.

**Comment by meitiever** [comment]
this is the last error i got:
from /home/steve/Documents/libseekthermal/src/lib/seekthermal/usb/interface.cpp:29:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
src/lib/seekthermal/usb/CMakeFiles/usb.dir/build.make:134: recipe for target 'src/lib/seekthermal/usb/CMakeFiles/usb.dir/interface.cpp.o' failed
make[3]: **\* [src/lib/seekthermal/usb/CMakeFiles/usb.dir/interface.cpp.o] Error 1
CMakeFiles/Makefile2:1314: recipe for target 'src/lib/seekthermal/usb/CMakeFiles/usb.dir/all' failed
make[2]: **\* [src/lib/seekthermal/usb/CMakeFiles/usb.dir/all] Error 2
CMakeFiles/Makefile2:234: recipe for target 'CMakeFiles/package_install.dir/rule' failed
make[1]: **\* [CMakeFiles/package_install.dir/rule] Error 2
Makefile:227: recipe for target 'package_install' failed
make: **\* [package_install] Error 2

could you help me out please. thanks.

**Comment by samuelba** [comment]
1. you have to install libudev-dev
2. is the last error related to libudev? On what platform are you trying to build (Ubuntu 16.04, NUC)?

**Comment by samuelba** [comment]
I built and installed libseekthermal successfully on a virtual machine with Ubuntu 16.04

**Comment by meitiever** [comment]
Hi samuelba
    1. Yes, I have installed libudev-dev.
    2. I have configured the build successfully. so i think it is not related to the libudev.
    3. OS version: 
        Distributor ID: Ubuntu
        Description:    Ubuntu 16.04.1 LTS
        Release:    16.04
        Codename:   xenial

**Comment by meitiever** [comment]
I think the error is from libseekthermal/src/lib/seekthermal/usb/interface.cpp line 29.
thanks

**Comment by meitiever** [comment]
Hi Samuelba
    Could you check the configuration output of libseekthermal.
    The first two lines of output:
     -- The C compiler identification is GNU 5.4.0
     -- The CXX compiler identification is GNU 5.4.0
    In the error output, I think the error caused by CXX complier of my NUC.
    What is the version of your CXX complier?

thanks

**Comment by meitiever** [comment]
I have figured out the this problem.
it is caused by g++ and c++11 feature has to be enabled before build.

thanks
